import { PAGE_MAP, PAGE_SPECS } from '../data/ia';
import visetos from '../assets/visetos-backpack.png';
import orange from '../assets/orange-crossbody.png';
import leather from '../assets/backpack.png';

const images=[visetos,orange,leather];
function Actions({spec,navigate}){return <div className="ia-actions">{spec.ctas?.map(([label,id],i)=><button className={i?'outline':''} onClick={()=>navigate(id)} key={label}>{label}<span>→</span></button>)}</div>}
function MapVisual(){return <div className="ia-map"><div className="ia-map-grid"/><span>WORLD / REGIONAL</span><i className="pin one"/><i className="pin two"/><i className="pin three"/><svg viewBox="0 0 600 280"><path d="M110 180 Q230 60 330 145 T510 95"/></svg></div>}
function FormVisual({layout}){return <div className="ia-form"><label>{layout==='auth'?'EMAIL':'CITY / PLACE'}<input placeholder={layout==='auth'?'you@email.com':'Tokyo, Japan'}/></label><label>{layout==='auth'?'PASSWORD':'DATE'}<input type={layout==='auth'?'password':'date'}/></label><label>{layout==='form'?'REQUEST TYPE':'SHORT NOTE'}<textarea placeholder="이야기를 짧게 기록하세요."/></label></div>}
function Layout({spec,navigate}){
  const f=spec.features||[];
  if(['product','product-detail','passport','register','products'].includes(spec.layout))return <div className="ia-product-layout"><div className="ia-product-image"><span>AUTHENTIC PRODUCT</span><img src={spec.id==='recommendation-detail'?orange:visetos}/><small>MMA · AVE1SC0001</small></div><div className="ia-product-info"><span>{spec.group}</span><h2>{spec.id==='recommendation-detail'?'AREN CROSSBODY':'STARK BACKPACK'}</h2><p>VISETOS ORIGINAL · COGNAC</p><div className="ia-facts">{f.map(x=><div key={x}><i/> {x}</div>)}</div><Actions spec={spec} navigate={navigate}/></div></div>;
  if(['map'].includes(spec.layout))return <><MapVisual/><div className="ia-feature-row">{f.map((x,i)=><article key={x}><b>0{i+1}</b><h3>{x}</h3><p>제품과 함께 쌓인 Story를 확인합니다.</p></article>)}</div><Actions spec={spec} navigate={navigate}/></>;
  if(['auth','form','journey-form'].includes(spec.layout))return <div className="ia-narrow"><FormVisual layout={spec.layout}/><div className="ia-chip-row">{f.slice(0,5).map(x=><button key={x}>{x}</button>)}</div><Actions spec={spec} navigate={navigate}/></div>;
  if(['complete','saved'].includes(spec.layout))return <div className="ia-complete"><div className="check">✓</div><h2>{spec.ko}</h2><p>{f.join(' · ')}</p><Actions spec={spec} navigate={navigate}/></div>;
  if(['story','share','content','community'].includes(spec.layout))return <><div className="ia-story-visual"><div><span>YOUR STORY WITH MCM</span><h2>낯선 도시에서,<br/>익숙한 나를 발견하는 시간.</h2><p>제품의 Story와 고객의 경험이 하나의 Archive로 이어집니다.</p></div><img src={visetos}/></div><div className="ia-timeline">{f.map((x,i)=><article key={x}><b>{String(i+1).padStart(2,'0')}</b><div><h3>{x}</h3><p>2026 · MCM ARCHIVE</p></div></article>)}</div><Actions spec={spec} navigate={navigate}/></>;
  if(['next','next-detail','recommendations'].includes(spec.layout))return <><div className="ia-context"><span>CUSTOMER CONTEXT</span><b>URBAN · WORK · EVERYDAY</b><p>기존 Journey와 제품 사용 맥락을 바탕으로 두 가지 Story만 제안합니다.</p></div><div className="ia-recommend-grid">{images.slice(1).map((img,i)=><article key={i}><span>RECOMMENDATION 0{i+1}</span><img src={img}/><h3>{i?'WEEKEND STORY':'DAILY MOVE'}</h3><p>{f[i]||'당신의 다음 Story를 완성할 경험'}</p></article>)}</div><Actions spec={spec} navigate={navigate}/></>;
  if(['timeline','archive','home'].includes(spec.layout))return <><div className="ia-dashboard"><article><span>JOURNEYS</span><strong>03</strong></article><article><span>CITIES</span><strong>02</strong></article><article><span>DAYS TOGETHER</span><strong>127</strong></article></div><div className="ia-timeline">{f.map((x,i)=><article key={x}><b>{i<3?`2026.${String(i+3).padStart(2,'0')}`:`0${i+1}`}</b><div><h3>{x}</h3><p>제품과 함께한 기록</p></div></article>)}</div><Actions spec={spec} navigate={navigate}/></>;
  if(['care','guide','settings'].includes(spec.layout))return <div className="ia-settings-grid">{f.map((x,i)=><article key={x}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{x}</h3><p>공식 MCM 정보와 상태를 확인합니다.</p></div><button>{spec.layout==='settings'?'●':'보기'}</button></article>)}<Actions spec={spec} navigate={navigate}/></div>;
  return <><div className="ia-feature-row">{f.map((x,i)=><article key={x}><b>0{i+1}</b><h3>{x}</h3><p>해당 기능의 상세 정보와 상태가 표시됩니다.</p></article>)}</div><Actions spec={spec} navigate={navigate}/></>;
}
export function IAPage({pageId,navigate}){const spec=PAGE_MAP[pageId];const index=PAGE_SPECS.findIndex(x=>x.id===pageId);return <main className="ia-page"><div className="ia-breadcrumb"><span>{spec.code}</span>{spec.group}</div><header className="ia-page-head"><div><span>{spec.title}</span><h1>{spec.ko}</h1></div><p>{String(index+1).padStart(2,'0')} / {PAGE_SPECS.length}</p></header><Layout spec={spec} navigate={navigate}/><footer className="ia-page-nav"><button disabled={!index} onClick={()=>navigate(PAGE_SPECS[index-1]?.id)}>← PREVIOUS</button><button disabled={index===PAGE_SPECS.length-1} onClick={()=>navigate(PAGE_SPECS[index+1]?.id)}>NEXT →</button></footer></main>}
export const createIAPage=pageId=>function Page({navigate}){return <IAPage pageId={pageId} navigate={navigate}/>};
