import { useEffect, useState } from 'react';
import { PAGE_MAP, PAGE_SPECS } from '../data/ia';
import { api } from '../api/client';
import visetos from '../assets/visetos-backpack.png';
import orange from '../assets/orange-crossbody.png';
import leather from '../assets/backpack.png';

const images=[visetos,orange,leather];
function Actions({spec,navigate}){return <div className="ia-actions">{spec.ctas?.map(([label,id],i)=><button className={i?'outline':''} onClick={()=>navigate(id)} key={label}><span>{label}</span><b>↗</b></button>)}</div>}
function EditorialImage({src=visetos,label='MCM ARCHIVE'}){return <figure className="editorial-image"><img src={src}/><figcaption><span>{label}</span><small>OBJECT · MEMORY · JOURNEY</small></figcaption></figure>}
function MapVisual(){return <div className="ia-map"><div className="ia-map-grid"/><span>WORLD / REGIONAL</span><i className="pin one"/><i className="pin two"/><i className="pin three"/><svg viewBox="0 0 600 280"><path d="M110 180 Q230 60 330 145 T510 95"/></svg></div>}
function FormVisual({layout}){return <div className="ia-form"><label><span>01</span>{layout==='auth'?'EMAIL':'CITY / PLACE'}<input placeholder={layout==='auth'?'you@email.com':'Tokyo, Japan'}/></label><label><span>02</span>{layout==='auth'?'PASSWORD':'DATE'}<input type={layout==='auth'?'password':'date'}/></label><label><span>03</span>{layout==='form'?'REQUEST TYPE':'SHORT NOTE'}<textarea placeholder="이야기를 짧게 기록하세요."/></label></div>}
function AIStoryLayout({navigate}){
  const [state,setState]=useState({loading:true,data:null,error:''});
  const generate=async()=>{setState({loading:true,data:null,error:''});try{const products=await api.myProducts();const current=products.find(x=>x.is_current)||products[0];if(!current)throw new Error('먼저 제품을 등록해주세요.');const data=await api.runAIPipeline(current.id);setState({loading:false,data,error:''})}catch(error){setState({loading:false,data:null,error:error.message})}};
  useEffect(()=>{generate()},[]);
  if(state.loading)return <section className="ai-live-state"><span className="ai-orbit"/><small>JOUME AI IS READING YOUR JOURNEY</small><h2>기록의 맥락을<br/>연결하고 있습니다.</h2></section>;
  if(state.error)return <section className="ai-live-state error"><small>AI JOURNEY STORY</small><h2>Story를 만들 수 없습니다.</h2><p>{state.error}</p><button onClick={()=>navigate(state.error.includes('로그인')?'login':'add-journey')}>{state.error.includes('로그인')?'로그인하기':'Journey 추가하기'} →</button></section>;
  const {context,story,next_stories:modelStories,model}=state.data;
  return <><section className="ia-story-visual reveal"><img src={visetos}/><div><span>AI JOURNEY STORY · {model}</span><h2>{story.title}</h2><p>{story.content}</p></div></section><section className="ai-context"><small>CUSTOMER CONTEXT</small><h3>{context.summary}</h3><div>{[...context.interests,...context.usage_purposes,...context.behavior_patterns].map(x=><span key={x}>{x}</span>)}</div></section><div className="ia-story-proposals">{modelStories.map((item,i)=><article key={item.id}><span>NEXT STORY · 0{i+1}</span><div><small>{item.city} · {item.activity}</small><h3>{item.theme}</h3><p>{item.reason}</p></div><button onClick={async()=>{await api.selectStoryWithAI(item.id);navigate('experience-recommendation')}}>이 Story 선택하기 <b>→</b></button></article>)}</div><div className="ia-actions"><button onClick={generate}><span>Story 다시 만들기</span><b>↻</b></button></div></>;
}
function Layout({spec,navigate}){
  const f=spec.features||[];
  if(spec.id==='ai-journey-story')return <AIStoryLayout navigate={navigate}/>;
  if(['product','product-detail','passport','register','products'].includes(spec.layout))return <section className="ia-product-layout reveal"><EditorialImage src={spec.id==='recommendation-detail'?orange:visetos} label="AUTHENTIC PRODUCT"/><div className="ia-product-info"><span>{spec.group}</span><h2>{spec.id==='recommendation-detail'?'AREN CROSSBODY':'STARK BACKPACK'}</h2><p>VISETOS ORIGINAL · COGNAC</p><blockquote>“모든 제품은 다음 장면을 기다리고 있습니다.”</blockquote><div className="ia-facts">{f.map((x,i)=><div key={x}><i>{String(i+1).padStart(2,'0')}</i>{x}</div>)}</div><Actions spec={spec} navigate={navigate}/></div></section>;
  if(['map'].includes(spec.layout))return <><MapVisual/><div className="ia-feature-row">{f.map((x,i)=><article key={x}><b>0{i+1}</b><h3>{x}</h3><p>제품과 함께 쌓인 Story를 확인합니다.</p></article>)}</div><Actions spec={spec} navigate={navigate}/></>;
  if(['auth','form','journey-form'].includes(spec.layout))return <section className="ia-form-stage reveal"><EditorialImage src={orange} label="YOUR NEXT CHAPTER"/><div className="ia-narrow"><FormVisual layout={spec.layout}/><div className="ia-chip-row">{f.slice(0,5).map(x=><button key={x}>{x}</button>)}</div><Actions spec={spec} navigate={navigate}/></div></section>;
  if(['complete','saved'].includes(spec.layout))return <div className="ia-complete"><div className="check">✓</div><h2>{spec.ko}</h2><p>{f.join(' · ')}</p><Actions spec={spec} navigate={navigate}/></div>;
  if(['story','share','content','community'].includes(spec.layout))return <><section className="ia-story-visual reveal"><img src={visetos}/><div><span>YOUR STORY WITH MCM</span><h2>낯선 도시에서,<br/>익숙한 나를<br/>발견하는 시간.</h2><p>제품의 Story와 고객의 경험이 하나의 Archive로 이어집니다.</p></div></section><div className="ia-timeline reveal">{f.map((x,i)=><article key={x}><b>{String(i+1).padStart(2,'0')}</b><div><h3>{x}</h3><p>2026 · MCM ARCHIVE</p></div></article>)}</div><Actions spec={spec} navigate={navigate}/></>;
  if(['next','next-detail'].includes(spec.layout))return <><div className="ia-context reveal"><span>NEXT STORY FOR YOU</span><b>RECORD → STORY → NEXT</b><p>구매 제안보다 먼저, 당신이 만들 다음 장면을 고릅니다.</p></div><div className="ia-story-proposals">{['새로운 시선','일상의 이동'].map((title,i)=><article key={title}><span>STORY THEME · 0{i+1}</span><div><small>{i?'BUSAN · SLOW WEEKEND':'SEOUL · DESIGN WALK'}</small><h3>{title}</h3><p>{i?'익숙한 제품과 함께 일상의 속도를 잠시 늦춰보세요.':'도시의 디자인과 건축을 따라 새로운 관점을 기록하세요.'}</p></div><button onClick={()=>navigate(i?'saved-next-story':'next-story-detail')}>이 Story 선택하기 <b>→</b></button></article>)}</div><Actions spec={spec} navigate={navigate}/></>;
  if(spec.layout==='recommendations')return <><div className="ia-context reveal"><span>BRAND EXPERIENCE</span><b>STORY → EXPERIENCE → PRODUCT</b><p>선택한 Story에 필요한 경험만 제한적으로 연결합니다.</p></div><div className="ia-recommend-grid">{images.slice(1).map((img,i)=><article key={i}><div className="recommend-image"><img src={img}/><span>0{i+1}</span></div><small>{i?'RELATED PRODUCT':'OFFICIAL EXPERIENCE'}</small><h3>{i?'A PIECE FOR THE NEXT CHAPTER':'MCM DESIGN WALK'}</h3><p>{f[i]||'선택한 Story를 실제 행동으로 이어주는 제안'}</p></article>)}</div><Actions spec={spec} navigate={navigate}/></>;
  if(['timeline','archive','home'].includes(spec.layout))return <><div className="ia-dashboard"><article><span>JOURNEYS</span><strong>03</strong></article><article><span>CITIES</span><strong>02</strong></article><article><span>DAYS TOGETHER</span><strong>127</strong></article></div><div className="ia-timeline">{f.map((x,i)=><article key={x}><b>{i<3?`2026.${String(i+3).padStart(2,'0')}`:`0${i+1}`}</b><div><h3>{x}</h3><p>제품과 함께한 기록</p></div></article>)}</div><Actions spec={spec} navigate={navigate}/></>;
  if(['care','guide','settings'].includes(spec.layout))return <div className="ia-settings-grid">{f.map((x,i)=><article key={x}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{x}</h3><p>공식 MCM 정보와 상태를 확인합니다.</p></div><button>{spec.layout==='settings'?'●':'보기'}</button></article>)}<Actions spec={spec} navigate={navigate}/></div>;
  return <><div className="ia-feature-row">{f.map((x,i)=><article key={x}><b>0{i+1}</b><h3>{x}</h3><p>해당 기능의 상세 정보와 상태가 표시됩니다.</p></article>)}</div><Actions spec={spec} navigate={navigate}/></>;
}
export function IAPage({pageId,navigate}){const spec=PAGE_MAP[pageId];const index=PAGE_SPECS.findIndex(x=>x.id===pageId);return <main className={`ia-page page-${spec.layout}`}><div className="ia-breadcrumb"><span>{spec.code}</span>{spec.group}</div><header className="ia-page-head reveal"><div><span>{spec.title}</span><h1>{spec.ko}</h1></div><p>ISSUE {String(index+1).padStart(2,'0')}</p></header><Layout spec={spec} navigate={navigate}/><footer className="ia-page-nav"><button disabled={!index} onClick={()=>navigate(PAGE_SPECS[index-1]?.id)}>← PREVIOUS</button><i>JOUME · BY MCM</i><button disabled={index===PAGE_SPECS.length-1} onClick={()=>navigate(PAGE_SPECS[index+1]?.id)}>NEXT →</button></footer></main>}
export const createIAPage=pageId=>function Page({navigate}){return <IAPage pageId={pageId} navigate={navigate}/>};
