import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import backpack from './assets/backpack.png';
import './styles.css';

const mainNav = ['COLLECTION', 'BAGS', 'WALLETS', 'ACCESSORIES', 'TRAVEL', 'MCM WORLD', 'SECOND JOURNEY'];
const steps = [
  ['01','진입 · 발견'],['02','등록 · 계정연결'],['03','JOURNEY 등록'],['04','JOURNEY HOME'],['05','MAP · TIMELINE'],['06','AI JOURNEY STORY'],['07','AI NEXT JOURNEY'],['08','PRODUCT CARE'],['09','MY MCM']
];

function go(page){ location.hash=`page-${page}`; window.scrollTo({top:0,behavior:'smooth'}); }
function Button({children,onClick,light=false,secondary=false}){return <button className={`${secondary?'secondary':'primary'} ${light?'light':''}`} onClick={onClick}>{children}</button>}

function Header({page}) {
  const [open,setOpen]=useState(false);
  return <><header className="header"><div className="header-inner">
    <button className="logo logo-button" onClick={()=>go(1)}>MCM</button>
    <nav className={`main-nav ${open?'open':''}`}>{mainNav.map(x=><a key={x} className={x==='SECOND JOURNEY'?'active':''} href="#page-4">{x}</a>)}</nav>
    <div className="utility"><button>⌕</button><button>◇</button><button>로그인</button><button>♡</button></div>
    <button className="menu" onClick={()=>setOpen(!open)}>{open?'×':'☰'}</button>
  </div></header><nav className="journey-nav"><div className="journey-inner">{steps.map(([n,t],i)=><button key={n} onClick={()=>go(i+1)} className={page===i+1?'active':''}><b>{n}</b> {t}</button>)}</div></nav></>;
}

function PageShell({number,kicker,title,desc,children,dark=false}){
  return <main className={`subpage ${dark?'dark-page':''}`}><section className="page-head container"><p className="page-number">{number} / 09</p><p className="eyebrow">{kicker}</p><h1>{title}</h1><p>{desc}</p></section>{children}</main>
}
function PageNav({page,next='다음 단계'}){return <div className="page-actions container">{page>1&&<Button secondary onClick={()=>go(page-1)}>← 이전</Button>} {page<9&&<Button onClick={()=>go(page+1)}>{next} →</Button>}</div>}
function ProductMini(){return <div className="product-mini"><img src={backpack}/><div><small>AUTHENTIC PRODUCT</small><h3>STARK BACKPACK</h3><code>MMA·AVE1SC0001</code></div></div>}

function Discover(){return <><section className="hero container"><div className="hero-copy"><p className="eyebrow">MCM SECOND JOURNEY</p><h1>모든 MCM 제품에는<br/>저마다의 스토리가<br/>담겨 있다.</h1><p className="intro">제품을 처음 발견한 순간부터 함께한 도시와 하루하루가 하나의 Journey가 됩니다.</p><Button light onClick={()=>go(2)}>START YOUR JOURNEY</Button></div><div className="hero-visual"><div className="grid-glow"/><div className="scanner-frame"><i className="corner tl"/><i className="corner tr"/><i className="corner bl"/><i className="corner br"/><img src={backpack}/><i className="scan-line"/></div><div className="stamp">MCM · TRAVEL<br/>HERITAGE<br/>EST. 1976</div><p className="passport-id">ID: MMA·AVE1SC<br/><b>DIGITAL PASSPORT ACTIVE</b></p></div></section><section className="passport container"><div className="product-panel"><p className="verified">◆ &nbsp;정품 인증됨</p><img src={backpack}/><h2>STARK BACKPACK<br/>IN VISETOS ORIGINAL</h2><code>MMA·AVE1SC0001</code></div><div className="info-panel"><p className="eyebrow orange">디지털 제품 여권</p><span className="status">• &nbsp;미연결</span><div className="facts"><div><small>소재</small><strong>VISETOS COATED CANVAS</strong></div><div><small>제조</small><strong>MADE IN KOREA</strong></div><div><small>구매일</small><strong>2024.04.12</strong></div><div><small>보증기간</small><strong>2026.04.11</strong></div></div><div className="story"><h3>제품 스토리</h3><p>MCM은 1976년 여행을 사랑하는 실용을 바탕으로 시작되었습니다. 여행과 이동을 담은 유산은 지금 당신의 이야기로 이어집니다.</p></div><div className="actions"><Button onClick={()=>go(2)}>두 번째 여정 시작하기</Button><Button secondary onClick={()=>go(8)}>제품 가이드 보기</Button></div></div></section><PageNav page={1} next="제품 등록"/></>}

function Register(){return <PageShell number="02" kicker="REGISTER & CONNECT" title={<>제품과 당신을<br/>연결합니다.</>} desc="제품의 NFC 태그 또는 고유 코드를 확인하고 MCM 계정에 연결하세요."><section className="split-card container"><div className="scan-box"><span>◇</span><h2>제품 태그 스캔</h2><p>스마트폰을 제품 내부의 NFC 태그에 가까이 대주세요.</p><div className="radar"><i/><i/><b>◆</b></div><Button>NFC 스캔 시작</Button></div><div className="form-panel"><p className="section-label">MANUAL REGISTRATION</p><h2>고유 코드로 등록</h2><label>제품 고유 코드<input defaultValue="MMA-AVE1SC0001"/></label><label>구매 경로<select defaultValue="official"><option value="official">MCM 공식 스토어</option><option>세컨드 핸드</option><option>선물</option></select></label><label className="check"><input type="checkbox" defaultChecked/> 정품 인증 및 제품 연결에 동의합니다.</label><Button onClick={()=>go(3)}>제품 연결하기</Button></div></section><PageNav page={2} next="Journey 설정"/></PageShell>}

function Setup(){const [selected,setSelected]=useState(0);const types=['TRAVEL','WORK','EVERYDAY','CELEBRATION','NEW BEGINNING'];return <PageShell number="03" kicker="RECORD A JOURNEY" title={<>제품과 함께한<br/>순간을 기록하세요.</>} desc="사진, 장소, 날짜와 짧은 메모만으로 첫 Journey를 만들 수 있습니다."><section className="record-layout container"><ProductMini/><div className="record-form"><div className="photo-drop"><span>＋</span><h3>사진 추가</h3><p>이 순간을 가장 잘 보여주는 사진 한 장</p><button>사진 선택</button></div><div className="record-fields"><p className="section-label">FIRST JOURNEY</p><label>Journey 제목<input defaultValue="Tokyo · First Business Trip"/></label><div className="field-row"><label>장소<input defaultValue="Tokyo, Japan"/></label><label>날짜<input type="date" defaultValue="2026-08-09"/></label></div><label>짧은 메모<textarea defaultValue="첫 해외 출장. 익숙한 가방과 낯선 도시를 걸었다."/></label><p className="input-title">경험 유형</p><div className="type-chips">{types.map((x,i)=><button className={selected===i?'selected':''} onClick={()=>setSelected(i)} key={x}>{x}</button>)}</div><Button onClick={()=>go(4)}>Journey 저장하기</Button></div></div></section><PageNav page={3} next="Journey Home"/></PageShell>}

function Home(){const timeline=[['2026.03','첫 출근','WORK · SEOUL'],['2026.08','첫 해외 출장','TRAVEL · TOKYO'],['2026.11','제품 케어','PRODUCT CARE · SEOUL']];return <PageShell number="04" kicker="MY JOURNEY" title={<>YOUR MCM.<br/>YOUR JOURNEY.</>} desc="제품과 함께한 경험이 지도와 시간 위에 하나의 Story로 쌓입니다." dark><section className="dashboard container"><div className="journey-card feature"><div><small>CURRENT JOURNEY · 127 DAYS</small><h2>SEOUL TO EVERYWHERE</h2><p>세 개의 도시, 열두 개의 순간</p><Button light onClick={()=>go(3)}>새 Journey 기록</Button></div><img src={backpack}/></div><div className="stat-row"><article><small>DAYS TOGETHER</small><strong>127</strong><p>함께한 날</p></article><article><small>CITIES VISITED</small><strong>03</strong><p>기록된 도시</p></article><article><small>JOURNEYS</small><strong>12</strong><p>저장된 경험</p></article></div><section className="timeline"><div className="timeline-head"><div><p className="section-label">JOURNEY TIMELINE</p><h2>시간이 Story가 되는 과정</h2></div><Button secondary onClick={()=>go(6)}>AI Story 만들기</Button></div>{timeline.map((x,i)=><article key={x[1]}><b>{x[0]}</b><i/><div><h3>{x[1]}</h3><p>{x[2]}</p></div><span>0{i+1}</span></article>)}</section></section><PageNav page={4} next="Map & Timeline"/></PageShell>}

function MapPage(){const places=[['SEOUL','12 MEMORIES','62 DAYS'],['BUSAN','04 MEMORIES','08 DAYS'],['TOKYO','06 MEMORIES','12 DAYS']];return <PageShell number="05" kicker="JOURNEY MAP" title={<>당신과 제품이 지나온<br/>도시의 기록.</>} desc="각 장소에 남겨진 순간을 선택해 Journey를 다시 만나보세요."><section className="map-layout container"><div className="map-art"><div className="map-lines"/><button className="pin p1">1</button><button className="pin p2">2</button><button className="pin p3">3</button><div className="map-label">37.5665° N<br/>126.9780° E</div></div><aside><p className="section-label">3 CITIES · 22 MEMORIES</p>{places.map((p,i)=><article key={p[0]}><span>0{i+1}</span><div><h3>{p[0]}</h3><p>{p[1]} · {p[2]}</p></div><b>→</b></article>)}</aside></section><PageNav page={5} next="Curated Tale"/></PageShell>}

function Tale(){const [saved,setSaved]=useState(false);return <PageShell number="06" kicker="AI JOURNEY STORY" title={<>흩어진 Journey가<br/>한 편의 Story로.</>} desc="AI는 고객이 남긴 사실만을 사용해 시간, 장소와 경험의 맥락을 연결합니다."><section className="ai-source container"><span>AI GENERATED FROM</span><div><b>03</b><small>JOURNEYS</small></div><div><b>02</b><small>CITIES</small></div><div><b>01</b><small>PRODUCT</small></div><p>제품 정보 · 장소 · 날짜 · 사진 · 메모 · 경험 유형</p></section><article className="editorial container"><div className="editorial-image"><img src={backpack}/><span>YOUR STORY WITH MCM</span></div><div className="editorial-copy"><p className="section-label">AI JOURNEY SUMMARY · 2026</p><h2>익숙한 동행과<br/>낯선 도시들</h2><blockquote>“서울에서 시작된 첫 출근의 긴장은 도쿄의 새로운 도전으로 이어졌습니다.”</blockquote><p>당신의 Stark Backpack은 일의 시작과 첫 해외 출장, 그리고 다시 일상으로 돌아온 순간을 함께했습니다. 제품을 오래 관리하려는 선택까지 모두 하나의 Journey입니다.</p><div className="actions"><Button onClick={()=>setSaved(true)}>{saved?'STORY 저장됨 ✓':'STORY 저장'}</Button><Button secondary>공유 카드 보기</Button></div></div></article><PageNav page={6} next="AI Next Journey"/></PageShell>}

function NextChapter(){const [picked,setPicked]=useState(0);const stories=[['BERLIN, NEW PERSPECTIVE','건축과 디자인을 따라 걷는 새로운 도시 이야기'],['A QUIET WEEKEND','가까운 바다에서 만드는 느린 주말의 이야기']];return <PageShell number="07" kicker="AI NEXT JOURNEY" title={<>WHERE WILL YOUR MCM<br/>TAKE YOU NEXT?</>} desc="AI는 상품이 아니라 당신이 다음에 만들 수 있는 Story 두 가지만 제안합니다." dark><section className="next-flow container"><p><b>STORY</b><span>→</span><b>EXPERIENCE</b><span>→</span><b>MCM CONNECTION</b></p></section><section className="story-options container">{stories.map((s,i)=><button key={s[0]} className={picked===i?'picked':''} onClick={()=>setPicked(i)}><span>0{i+1} · NEXT STORY</span><h2>{s[0]}</h2><p>{s[1]}</p><b>{picked===i?'SELECTED ✓':'SELECT THIS STORY →'}</b></button>)}</section><section className="experience-links container"><p className="section-label">CONNECTED TO YOUR SELECTED STORY</p><div className="chapter-grid"><article><span>EXPERIENCE</span><h3>Berlin Design Weekend</h3><p>도시의 건축과 디자인 아카이브를 따라가는 2박 3일 큐레이션</p><Button light>경험 저장</Button></article><article><span>PRODUCT CARE</span><h3>여행 전 제품 케어</h3><p>가까운 공식 매장: MCM Seoul</p><Button secondary onClick={()=>go(8)}>케어 예약</Button></article><article><span>MCM CONTENT</span><h3>Berlin City Guide</h3><p>MCM이 고른 공간과 문화 콘텐츠</p><Button secondary>콘텐츠 보기</Button></article></div></section><PageNav page={7} next="Product Care"/></PageShell>}

function Care(){const tips=[['01','부드럽게 닦기','마른 극세사 천으로 표면의 먼지를 제거하세요.'],['02','습기를 피하기','젖었을 때는 그늘지고 통풍이 잘 되는 곳에서 건조하세요.'],['03','형태를 지키기','보관 시 내부를 채우고 더스트 백을 사용하세요.']];return <PageShell number="08" kicker="PRODUCT CARE" title={<>오래 함께하기 위한<br/>작은 습관.</>} desc="제품의 소재와 사용 기록을 바탕으로 맞춤 관리 방법을 안내합니다."><section className="care-hero container"><img src={backpack}/><div><p className="verified">◆ &nbsp;CARE STATUS · GOOD</p><h2>VISETOS COATED CANVAS</h2><p>마지막 케어 기록으로부터 42일이 지났습니다. 간단한 표면 클리닝을 권장합니다.</p><div className="care-meter"><i/></div><Button>케어 완료 기록하기</Button></div></section><section className="care-tips container">{tips.map(t=><article key={t[0]}><b>{t[0]}</b><h3>{t[1]}</h3><p>{t[2]}</p></article>)}</section><PageNav page={8} next="My MCM"/></PageShell>}

function MyMcm(){return <PageShell number="09" kicker="MY MCM" title={<>나의 제품과 기록,<br/>하나의 아카이브.</>} desc="소유한 제품과 Journey, 케어 정보를 한곳에서 관리하세요."><section className="profile-bar container"><div className="avatar">JH</div><div><h2>JOOHO'S ARCHIVE</h2><p>MEMBER SINCE 2024 · SEOUL</p></div><Button secondary>프로필 설정</Button></section><section className="my-grid container"><article className="my-product"><p className="section-label">MY PRODUCT · 01</p><img src={backpack}/><h3>STARK BACKPACK</h3><p>CONNECTED · 2024.04.12</p></article><div className="my-summary"><article><p>JOURNEY</p><strong>127</strong><span>DAYS</span></article><article><p>MEMORIES</p><strong>12</strong><span>STORIES</span></article><article><p>CITIES</p><strong>03</strong><span>VISITED</span></article><button onClick={()=>go(4)}><span>CONTINUE JOURNEY</span><b>현재 Journey로 돌아가기 →</b></button></div></section><PageNav page={9}/></PageShell>}

const pages=[Discover,Register,Setup,Home,MapPage,Tale,NextChapter,Care,MyMcm];
function App(){const read=()=>Math.min(9,Math.max(1,Number(location.hash.match(/page-(\d+)/)?.[1]||1)));const [page,setPage]=useState(read);useEffect(()=>{const f=()=>setPage(read());addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]);const Page=pages[page-1];return <><Header page={page}/><Page/><footer><span>MCM WORLDWIDE. © ALL RIGHTS RESERVED.</span><span>고객센터 · 이용약관 · 개인정보처리방침</span></footer></>}
createRoot(document.getElementById('root')).render(<App/>);
